[[footer]]
URL = "about"
name = "The Journey"
[[footer]]
URL = "service"
name = "Aevatar"
[[footer]]
URL = "insights"
name = "Insights"
[[footer]]
URL = "contact"
name = "Connect"
[[footer]]
URL = "career"
name = "Careers"
[[main]]
URL = "aevetar"
name = "Aevetar"
weight = "3"
[[main]]
URL = "roadmap"
name = "The Journey"
weight = 2
[[main]]
URL = "insights"
name = "Insights"
weight = 4
[[main]]
URL = "contact"
name = "Connect"
weight = 5
[[main]]
URL = "career"
hasChildren = true
name = "Careers"
weight = 6
