[[footer]]
URL = "career"
name = "Careers"
[[footer]]
URL = "contact"
name = "Contact Us"
[[footer]]
URL = "insights"
name = "Insights"
[[footer]]
URL = "aevetar"
name = "Aevatar"
[[footer]]
URL = "roadmap"
name = "Roadmap"
[[main]]
URL = "aevetar"
name = "Aevetar"
weight = "3"
[[main]]
URL = "roadmap"
name = "Roadmap"
weight = 2
[[main]]
URL = "insights"
name = "Insights"
weight = 4
[[main]]
URL = "contact"
name = "Contact Us"
weight = 5
[[main]]
URL = "career"
hasChildren = true
name = "Careers"
weight = 6
