address = "Global"
author = ""
contact_form_action = "https://getform.io/f/1acca456-6550-4f61-883a-008eacd510c9"
custom_script = ""
description = "This is meta description"
email = "hello@xaegir.io"
favicon = "images/favicon.png"
google_analitycs_id = "Your ID"
image = "images/logo-2.svg"
logo = "images/logo-2.svg"
mainSections = []
mobile = ""
search = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By viewing this website, you agree to XAEGIR's use of cookies."
enable = true
expire_days = 2
[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_label = "XAEGIR"
map_zoom = 17
[navigation_button]
enable = true
label = "Discord"
link = "https://discord.gg/EhmxUVtncr"
[preloader]
enable = true
preloader = "images/preloader.gif"
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[selectedsocial]]
icon = "fab fa-twitter"
link = "https://twitter.com/xaegir_"
title = "twitter"
[[selectedsocial]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/xaegir_"
title = "instagram"
[[social]]
icon = "fab fa-discord"
link = "https://discord.gg/EhmxUVtncr"
title = ""
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/xaegir_"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/xaegir_/"
title = "instagram"
