[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[params.variables]
bg_gradient_primary = "linear-gradient(134deg, #000000 0%, #000000 100%)"
bg_gradient_secondary = "linear-gradient( 80deg, rgb(0,48,204) 0%, #000000) 100%)"
bg_secondary = "#000000"
black = "#000"
border_color = "#000000"
btn_gradient_primary = "linear-gradient(45deg, #ffffff 0%, #000000 100%)"
gray = "#8b8e93"
icon_font = "Font Awesome 5 Free"
primary_color = "#ffc0cb "
primary_font = "Poppins:wght@300;400;500;600;700"
primary_font_type = "sans-serif"
roadmap_background = "#800080"
secondary_color = "#000000"
secondary_font = "Open Sans:wght@300;400;600;700;800"
secondary_font_type = "sans-serif"
text_color = "#8b8e93"
text_color_light = "#959595"
text_dark = "#242f3e"
text_light = "#d4dae3"
white = "#fff"
