[[footer]]
URL = "about"
name = "Company History"
[[footer]]
URL = "about"
name = "About us"
[[footer]]
URL = "contact"
name = "Contact us"
[[footer]]
URL = "service"
name = "Services"
[[footer]]
URL = "#"
name = "Privacy Policy"
[[main]]
URL = "about"
name = "Roadmap"
weight = 2
[[main]]
URL = "service"
name = "Service"
weight = 3
[[main]]
URL = "blog"
name = "Blog"
weight = 4
[[main]]
URL = "contact"
name = "Contact"
weight = 5
[[main]]
hasChildren = true
name = "Pages"
weight = 6
[[main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[main]]
URL = "career"
name = "Career"
parent = "Pages"
[[main]]
URL = "team"
name = "Team"
parent = "Pages"
[[main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[main]]
URL = "changelog"
name = "Changelog"
parent = "Pages"
