[[footer]]
URL = "about"
name = "Careers"
[[footer]]
URL = "about"
name = "Insights"
[[footer]]
URL = "service"
name = "Roadmap"
[[footer]]
URL = "contact"
name = "Contact us"
[[main]]
URL = "roadmap"
name = "Roadmap"
weight = 2
[[main]]
URL = "insights"
name = "Insights"
weight = 4
[[main]]
URL = "service"
name = "Service"
weight = 3
[[main]]
URL = "contact"
name = "Contact"
weight = 5
[[main]]
URL = "team"
hasChildren = true
name = "Careers"
weight = 6
