[[footer]]
URL = "about"
name = "Careers"
[[footer]]
URL = "about"
name = "Insights"
[[footer]]
URL = "service"
name = "Roadmap"
[[footer]]
URL = "contact"
name = "Contact us"
[[main]]
URL = "about"
name = "Roadmap"
weight = 2
[[main]]
URL = "blog"
name = "Insights"
weight = 4
[[main]]
URL = "service"
name = "NFT "
weight = 3
[[main]]
hasChildren = true
name = "Careers"
weight = 6
[[main]]
URL = "contact"
name = "Contact Us"
weight = 5
