[[footer]]
URL = "about"
name = "Company History"
[[footer]]
URL = "about"
name = "About us"
[[footer]]
URL = "contact"
name = "Contact us"
[[footer]]
URL = "service"
name = "Services"
[[footer]]
URL = "#"
name = "Privacy Policy"
[[main]]
URL = "about"
name = "Roadmap"
weight = 2
[[main]]
URL = "blog"
name = "Insights"
weight = 4
[[main]]
URL = "service"
name = "NFT "
weight = 3
[[main]]
hasChildren = true
name = "Jobs"
weight = 6
[[main]]
URL = "contact"
name = "Contact"
weight = 5
