---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry"
webhook_url: 
sections:
- type: heading
  label: Localization
- type: document
  path: xaegir/i18n/en.yaml
  label: i18n
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/english/career
  label: career
  create: all
  match: "**/*"
- type: directory
  path: content/english/insights
  label: Insights
  create: all
  match: "*"
- type: document
  path: content/english/roadmap/**/*
  label: Roadmap
- type: directory
  path: content/english
  label: Pages
  create: all
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Config
- type: document
  path: config/_default/menus.en.toml
  label: Menus
- type: document
  path: config/_default/languages.toml
  label: Languages
upload_dir: static/images/**/*
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public --themesDir
    ../..
version: 0.80.0
